name: run-gradle
description: Install Java and run gradle tasks
inputs:
  args:
    description: Add command-line arguments into gradle command
    required: true
  packages-github-token:
    description: Auth token to load Github packages
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Java version
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'liberica'
        cache: 'gradle'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Check with Gradle
      shell: sh
      run: ./gradlew --no-daemon --warning-mode none -i -PRsmIntegrationsSdkUsername=${{ github.actor }} -PRsmIntegrationsSdkPassword=${{ inputs.packages-github-token }} ${{ inputs.args }}
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ inputs.packages-github-token }}
